[build-system]
requires = ["flit_core >=3.2,<4", "tqdm"]
build-backend = "flit_core.buildapi"

[project]
name = "ts_datasets"
authors = [{name = "Stephen Fox", email = "gh@stephenjfox.com"}]
readme = "README.md"
dynamic = ["version", "description"]
